let allLinks = [
  'https://findtheinvisiblecow.com/',
  'https://randomthingstodo.com/',
  'https://badhtml.com/',
  'https://whereisthesloth.com/',
  'https://setwithfriends.com/',
  'http://orteil.dashnet.org/cookieclicker/',
  'https://cat-bounce.com/',
  'http://play.elevatorsaga.com/',
  'https://www.keybr.com/',
  'http://www.foddy.net/Athletics.html',
  'https://www.window-swap.com/',
  'https://procatinator.com/',
  'http://www.omfgdogs.com/',
  'https://heeeeeeeey.com/',
  'http://www.koalastothemax.com/',
  'https://benedictcumberbatchgenerator.tumblr.com/',
  'http://www.donothingfor2minutes.com/',
  'https://longdogechallenge.com/',
  'https://smashthewalls.com/',
  'https://jacksonpollock.org/',
  'http://www.slightlyinteresting.com/plasmaglobe/plasma.asp',
  'https://quickdraw.withgoogle.com/',
  'http://www.clicktoremove.com/',
  'https://www.pointless.com/',
  'https://isitchristmas.com/',
];

export default allLinks;
